### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by xuhuajie990** [sahibgasimov/eks-terraform-stable#2]
First of all thank you for your wonderful content；

I have a configuration question，as follows:

What does 6.20.3 and 1.5.3 mean here?  Where can these be obtained?

 ##### ALB Ingress Controller and External DNS #####
  external_dns          = "6.20.3"
  alb_ingress           = "1.5.3"
  alb_ingress_image_tag = "v2.5.2"

**Comment by sahibgasimov** [comment]
@xuhuajie990 I'm glad you found this helpful!

external_dns = "6.20.3" and alb_ingress = "1.5.3":
These values represent the versions of the external DNS and ALB Ingress Controller software in EKS cluster. The numbers "6.20.3" and "1.5.3" are version numbers of the respective software packages. These versions indicate which release of the software you want to use for your EKS cluster. These versions could include bug fixes, improvements, or new features introduced since previous versions. You can find versions in their respective helm artifacts  https://artifacthub.io/packages/helm/bitnami/external-dns?ref=christian-knell

alb_ingress_image_tag = "v2.5.2":
This is a specific tag associated with the Docker image of the ALB Ingress Controller. Docker images are typically versioned using tags to indicate different versions or releases of the software. In this case, "v2.5.2" refers to a specific release of the ALB Ingress Controller Docker image.

Let me know if you have more questions!
Sahib

**Comment by jpriolo** [comment]
Hello Sahib, 
    Thanks for this amazing re-usable code.
    One issue I'm having is when I run "terraform apply", I get prompted for all of the variables in the module.tf file I modified.
Q: WHERE exactly should the module.tf file reside? And should it have a different file name?

Sorry , Im a bit of a TF noob. Thanks again.

Joseph P.
priolo.joseph@gmail.com
https://github.com/jpriolo

**Comment by sahibgasimov** [comment]
@jpriolo Hi.  

you have to be inside the module folder to run terraform commands . Use example.tf to configure your values 

If you have more questions please open a new Issue.

Thanks
